module.exports = () => ( {
	plugins: {
		'postcss-import': {},
		'postcss-url': {},
		'postcss-for': {},
		'postcss-each': {},
		'postcss-mixins': {},
		'postcss-custom-selectors': {},
		'postcss-selector-replace': {
			before: [ '[prefix]' ],
			after: [ 'sixa-extras' ],
		},
		'postcss-important-startstop': {},
		'postcss-nested-ancestors': {},
		'postcss-nested': {},
		'postcss-variables-prefixer': {
			prefix: 'sixa-',
			ignore: [ /range/ ],
		},
		'postcss-extend': {},
		'postcss-if-media': {},
		'postcss-custom-media': {},
		'postcss-quantity-queries': {},
		'postcss-start-to-end': {},
		'postcss-calc': {},
		'postcss-size': {},
		'postcss-flexbox': {},
		'postcss-position': {},
		'postcss-hidden': {},
		'postcss-short-border-radius': {},
		'postcss-transform-shortcut': {},
		'postcss-selector-not': {},
		'postcss-combine-media-query': {},
		'postcss-combine-duplicated-selectors': {},
		'postcss-discard-empty': {},
		'postcss-input-range': {},
		autoprefixer: { grid: true },
	},
} );
